version: "3.8"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
        REDIS_URL: "redis://:pass@redis:6379/0"
        TEST_REDIS_URL: "redis://:pass@test_redis:6379/0"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass pass

  test_redis:
    image: "redis:alpine"
    volumes:
      - ./data/test_redis:/data
    command: redis-server --requirepass pass
